### ISSUE TITLE
xy_tiling setting when process own data

### ISSUE THREAD

**Issue by QingXia1994** [drprojects/superpoint_transformer#103]
where should i modify when i need to SampleXYTiling by specific range like 100m*100m instead of by regular XY grid with xy_tiling².

thanks a lot !

**Comment by drprojects** [comment]
This is not a functionality we support. We only support `SampleXYTiling` and `SampleRecursiveMainXYAxisTiling`. These operate splitting operations "blindly" in the sense that they are not targeting a specific tile size but rather obey a required number of splits. 

I agree this could be an interesting feature. This could be implemented within `SampleXYTiling`, as an extra argument. This would also mean that the following functions should be adapted: `BaseDataset.get_tile_from_path()`, `BaseDataset.all_cloud_ids()`, and `BaseDataset._process_single_cloud()`.

Feel free to create a Pull Request if you implement this ! :wink:
