### ISSUE TITLE
ModuleNotFoundError: No module named 'src.dependencies.FRNN'

### ISSUE THREAD

**Issue by m-sakha** [drprojects/superpoint_transformer#104]
I tried running the demo on Colab notebook, I am getting the following error:

superpoint_transformer-master/src/utils/neighbors.py in <module>

```
      1 import torch
      2 import src
----> 3 from src.dependencies.FRNN import frnn
      4 from torch_scatter import scatter
      5 from torch_geometric.utils import coalesce
```

ModuleNotFoundError: No module named 'src.dependencies.FRNN'

**Comment by drprojects** [comment]
This means FRNN has not been properly installed. Likely a compilation issue. Check out the other FRNN-related issues in this project to debug your case.

Although I must warn you, we have not tested installing this project in a Colab, and we do not provide support for it.

PS: if you ❤️ or use this project, don't forget to give it a ⭐, it means a lot to us !
