### ISSUE TITLE
Error when installing pgeof.

### ISSUE THREAD

**Issue by Wind010321** [drprojects/superpoint_transformer#111]
Hello, when I build the environment following the install.sh,I encounter an error as follows:
![截屏2024-05-25 13 01 15](https://github.com/drprojects/superpoint_transformer/assets/74442617/2c6e68ae-6842-4107-a64a-98cecf709749)

![截屏2024-05-25 13 00 54](https://github.com/drprojects/superpoint_transformer/assets/74442617/d383f950-d76f-4f1c-9ec0-6a0262498398)

I have tried many times but not find the solutions. My python version is 3.8 and the torch's version is 2.2.0, cuda's version is 11.8.
Can you give me some solutions?
Thanks!

**Comment by drprojects** [comment]
This may be related to #102. Can you please try the tentative fixes proposed in the thread and let me know if that solves your problem ?

**Comment by Wind010321** [comment]
Sorry, the command "conda install -c conda-forge libstdcxx-ng" does not solve my problem.And the error proposed is the same as the original one.

**Comment by Wind010321** [comment]
I just want to use the partition level L1 and L2 superpoints as the input of my network. But at the beginning of the installation part, I get the error. Is there any other solution that you can provide?

**Comment by Wind010321** [comment]
I noticed that the supported python version of pgeof >=3.9. Should I change the python's version  to 3.9 and install from scratch?

**Comment by drprojects** [comment]
Ok can you please try installing only pgeof in a fresh environment ? Refer to https://pypi.org/project/pgeof for that. If the error persists, this is a pgeof-specific error. In which case please open an issue on: https://github.com/drprojects/point_geometric_features

**Comment by Wind010321** [comment]
It is so sad that the error still exists.

**Comment by Wind010321** [comment]
It is happy that I successfully install the pgeof using command "python -m pip install pgeof".  
![截屏2024-05-26 16 54 37](https://github.com/drprojects/superpoint_transformer/assets/74442617/05ba386b-e2ee-4d1b-bae6-69f956439f87)

Yesterday I have used this command line but failed to install it. I will figure it out in the last hours to give you some possible reasons.

**Comment by Wind010321** [comment]
Hi, I find out that the clean conda environment is the key. Use the command "conda clean" might help.
I have solve my problem and I will close the issue.
Thanks for your patience!

**Comment by Avril-Dragon** [comment]
I also encountered the same difficulty and could not solve

**Comment by Wind010321** [comment]
I have created this conda environment for more that 4 times. Just run the ./install.sh and you will make it!

**Comment by Wind010321** [comment]
> I have created this conda environment for more that 4 times. Just run the ./install.sh and you will make it!

I have created this conda environment for more that 4 times. Just run the ./install.sh and you will make it!
