### ISSUE TITLE
Is my format of the Scannetv2 wrong?

### ISSUE THREAD

**Issue by Wind010321** [drprojects/superpoint_transformer#112]
Hi, I set the Scannetv2 as the datasets.md descripted. But there is an error as below:
![截屏2024-05-27 18 21 02](https://github.com/drprojects/superpoint_transformer/assets/74442617/1c9be0ed-424f-41ff-a0c8-2cc10f6942a2)

My dataset's format is correct as below:
![截屏2024-05-27 18 24 44](https://github.com/drprojects/superpoint_transformer/assets/74442617/4fa32754-d0ce-4e58-b3eb-5592b8ea3a4e)
![截屏2024-05-27 18 24 28](https://github.com/drprojects/superpoint_transformer/assets/74442617/aa65103f-4029-4162-873d-c2203ae73d04)

What is the problem of my format?

**Comment by Wind010321** [comment]
It seems that the "scans_test" folder is not recognized correctly.

**Comment by drprojects** [comment]
Aren't you missing `scannetv2-labels.combined.tsv` ?

**Comment by Wind010321** [comment]
I have add that .tsv into the folder.
![截屏2024-05-27 19 04 54](https://github.com/drprojects/superpoint_transformer/assets/74442617/38eeecdc-f49a-453b-9588-010faea82b47)

**Comment by Wind010321** [comment]
I originally only set the "scans" without the "scans_test". I think there maybe some cache in the logs or the "processed" folder. I just delete them and preprocess again.

**Comment by Wind010321** [comment]
The error still exists. I just create the correct environment, then put the scannetv2 data on the correct path. I don't change the content of any other files.

**Comment by drprojects** [comment]
@Wind010321 this was the second issue you opened in one day, and both turned out to be coming from errors on your end. Providing support for issues is time-consuming for us. So please be mindful, and **thoroughly investigate first before opening an issue here**.
