### ISSUE TITLE
shapenet dataset 

### ISSUE THREAD

**Issue by meehirmhatrepy** [drprojects/superpoint_transformer#119]
what modifications would make this approach work with shapenet dataset where the goal is to segment parts of pointclouds like Aeroplane, Bike, etc. which are not necessarily aligned with axis.
Any suggestions would be of great help.
Thankyou.

**Comment by drprojects** [comment]
Our method is essentially built for dealing with very large scenes of varying sizes. ShapeNet, on the other hand, is an easier setup with isolated objects, without acquisition artifacts, and reduced number of points. Yet, Superpoint Transformer should definitely work on ShapeNet too. You would obviously need to adapt the preprocessing parametrization to adjust to the desired voxel resolution, partition coarsness, partition graph size, etc. It would definitely be an interesting to this project, feel free to send us a pull request if you implement a new ShapeNet dataset !

**Comment by meehirmhatrepy** [comment]
Would you please guide me with  few parameters to change please?
I have a custom dataset of various types bottles in which i wish to do part segmentation like outer part, lid, base, etc.
As there is no alignment in point clouds with respect to z axis, the predictions are very off.
how do i avoid this?
Like what if a point clouds are not aligned  with respect to z axis ?
