### ISSUE TITLE
How to train in different devices?

### ISSUE THREAD

**Issue by Wind010321** [drprojects/superpoint_transformer#123]
Hello,
  If I have 4 gpu in 1 node, and I want to separately train a model in one gpu.(such as training1 -> gpu0, training2 -> gpu1...)
  So how do I specify a gpu for training?(such as gpu0, gpu1).

**Comment by drprojects** [comment]
The code is based on the [lightning hydra template](https://github.com/ashleve/lightning-hydra-template), which itself builds on PyTorch lightning. Please have a look at the corresponding documentations:
- [lightning hydra template](https://github.com/ashleve/lightning-hydra-template?tab=readme-ov-file#your-superpowers)
- [lightning choosing device](https://lightning.ai/docs/pytorch/stable/accelerators/gpu_basic.html#choosing-gpu-devices)

**Comment by Wind010321** [comment]
Thank you!
