### ISSUE TITLE
How to get the super_index_raw_to_level0?

### ISSUE THREAD

**Issue by Wind010321** [drprojects/superpoint_transformer#124]
Hello, 
    I find in demo.ipynb: "If we want to do full-resolution predictions, we need to [set the parameter to true](https://github.com/drprojects/superpoint_transformer/blob/7af051f9763e41e4564b046368d4af2fd74ea4b9/notebooks/demo.ipynb#L91) ."
    I want to get the 'sub' to obtain the "sub_level0_to_raw" parameter. I have set "load_full_res_idx: true". When I load the .h5 file to see if the P0 has the key 'sub', there isn't a sub but have these below:
<img width="1486" alt="截屏2024-06-30 20 52 58" src="https://github.com/drprojects/superpoint_transformer/assets/74442617/d9094b81-ac91-402a-b055-627abee3ea5f">
    1. I want to obtain the sub_level0_to_raw, so the 'pointers' is what I want(i.e. sub_level0_to_raw=pointers)?
    2. I want to assign the P0's index to the point in the raw data, what can i do based on 'pointers' and 'points'?
<img width="490" alt="截屏2024-06-30 21 22 17" src="https://github.com/drprojects/superpoint_transformer/assets/74442617/d47cbf2f-d183-4d0b-b021-e1b581309e23">
Thank you!

**Comment by drprojects** [comment]
If I understand well: the `'sub'` key is indeed present in your HDF5 and `load_full_res_idx=True` ? This should normally work then. Have you tried killing your notebook kernel and restarting it ? After which, make sure your `dataset.point_load_keys` contains `'sub'`, this is what `load_full_res_idx=True` should trigger. To this end check:

```python
# Make sure 'sub' is among the point_load_keys
print(datamodule.val_dataset.point_load_keys)
```

**Comment by Wind010321** [comment]
I experimentally make sure that the `'sub'` key is the In the '_cluster_' as showed in the first questions I posted where I can get the 'points' and the 'pointers'. Provide some explanations for this question. I solved my problem and I'll close this issue.
