### ISSUE TITLE
stuff_classes

### ISSUE THREAD

**Issue by ImaneTopo** [drprojects/superpoint_transformer#125]
hello Mr.Damien, during the training of the model on my own dataset whish contains 2 classes : pomme(apple) and clutter, normally the instances are apples, I don't know how to fix the stuff_classes
![image](https://github.com/drprojects/superpoint_transformer/assets/172318710/d372e8c0-5f2f-4a64-b89c-04ee4cb694b0)

**Comment by drprojects** [comment]
If you are doing apple panoptic segmentation, you should have set your dataset to have 'clutter' as the only 'stuff' class and apple is, as a result, the only 'thing'  class.

Have a look at the code for `BaseDataset.stuff_classes`, it is fairly documented and straightforward. See also the provided datasets and how 'thing' and 'stuff' classes are declared and handled.

### If you ❤️ or use this project, don't forget to give it a ⭐, it means a lot to us !

**Comment by ImaneTopo** [comment]
> BaseDataset.stuff_classes
Here : [0, self.num_classes-1]  , is self.num_classes-1 means the number of class wish is stuff like in my case clutter , os if I have 
1 pomme
2 clutter 
the self.num_classes  =,2 ??
