### ISSUE TITLE
Missing function instantiate_datamodule_transforms()

### ISSUE THREAD

**Issue by tejaswi-digumarti-oxb** [drprojects/superpoint_transformer#126]
In the file [superpoint_transformer_tutorial.ipynb](https://github.com/drprojects/superpoint_transformer/blob/master/notebooks/superpoint_transformer_tutorial.ipynb) section 4.1 says to use the function `instantiate_datamodule_transforms` to convert the `cfg.datamodule` to a `transforms_dict`. 

This function does not exist. How do I instantiate the `transforms_dict` ? Is there an alternate way?

**Comment by drprojects** [comment]
Indeed, seems like part of my last commit had been lost in the process. Just pushed missing files, should fix the issue.

PS: **If you ❤️ or use this project, don't forget to give it a ⭐, it means a lot to us !**
