### ISSUE TITLE
fatal error: eigen3/Eigen/Dense: No such file or directory

### ISSUE THREAD

**Issue by jhbae1184** [drprojects/superpoint_transformer#13]
Thank you for your hard working.
When i run `install.sh`, I have some issue.
Especially in installing point geometric features, there are the problem :

```bash
fatal error: eigen3/Eigen/Dense: No such file or directory
````

I think it is cpp config error, but sorry i dont have any idea about this solution..
Can you help me? 
Thank you already !

**Comment by drprojects** [comment]
Hi @jhbae1184, thanks for using this project !

So, it seems you are missing the `eigen3` library, which should have been installed by [this line in `instal.sh`](https://github.com/drprojects/superpoint_transformer/blob/6b9ac9aa0c96d843af7f50448a3fbf968263d56a/install.sh#L112C6-L112C6):

```bash
conda install -c omnia eigen3 -y
````

Can you please make sure this command did not fail ?

If the error persists, please share the whole log from `install.sh`, so I can see what might be happening.

**Comment by jhbae1184** [comment]
Thank you for replying fast !
Ahh, okay. I check that line that the libraries are installed or not. If not working, i will say to you again.

**Comment by jhbae1184** [comment]
Hi, @drprojects ! 
I check that library installed following your answer, but the error doesnt solve..

the whole error log is like this:
cl : Command line warning D9002: Ignoring unknown '/std:c++11' option.
pgeof_cpy.cpp
./pgeof_cpy.cpp(1): warning C4819: The file contains characters that cannot be represented in the current code page (949). Save the file in Unicode format to avoid data loss.
C:\python\gnn\Medical\superpixel_pointcloud\superpoint_transformer\src\dependencies\point_geometric_features\python\../src/pgeof.cpp(4): fatal error C1083: Could not open include file. 'eigen3/Eigen/Dense': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

And I`m sorry but i also have one more problem.. 
they can`t find frnn (not installed) so when i checked the log :

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120

I'm new to programming, so I can't figure out the cause of the following error. I'm sorry, but could you please take a look at the following reason?
Sorry and thank you again !

**Comment by drprojects** [comment]
Your error logs seem to indicate your are using a Windows machine. As stated in the [Environment requirements](https://github.com/drprojects/superpoint_transformer#--environment-requirements]), this project was only tested for a Linux OS. I **cannot provide support for Windows**, sorry :information_desk_person:

Feel free to reopen this issue if you are encountering the same problem on a machine compliant to our [Environment requirements](https://github.com/drprojects/superpoint_transformer#--environment-requirements]).
