### ISSUE TITLE
Point cloud with intensity and without RGB.

### ISSUE THREAD

**Issue by zeejja** [drprojects/superpoint_transformer#130]
Greetings,

First of all, thank you very much for the effort put into this repository and the articles. It's really impressive. I just have a small question before conducting the experiment with my personalized data. I want to know if I can use it on my custom point cloud data that only contains XYZ + intensity information without RGB information, or on data that includes both RGB and intensity information. Thank you for your effort, I am looking forward to your response.

**Comment by drprojects** [comment]
Hi @zeejja, thanks for your interest in the project !

Yes of course you can use any combinations of {XYZ, intensity, RGB}. Have a look at our already-implemented datasets and the corresponding configs to see how to handle your point attributes. For instance, DALES has XYZ+intensity, while S3DIS, ScanNet, and KITTI-360 have XYZ+RGB. None of those actually use both intensity and RGB, but it would be possible configure your dataset for it. To this end, have a look at the `partition_hf` and `point_hf` in the datamodule configs:
- `partition_hf` indicates the point attributes that should be used for the partition computation
- `point_hf` indicates the point attributes that should be loaded from disk and used for learning

As long as your dataset's `read_single_raw_cloud()` returns a `Data` object with `rgb` and `intensity` attributes, implementing what you want should be straightforward.

Happy coding !
