### ISSUE TITLE
About config parameters of the new dataset

### ISSUE THREAD

**Issue by Rambler30** [drprojects/superpoint_transformer#131]
Hello, thank you for your wonderful work. But I have some small problems. According to what standard should the parameters such as per-transformer, transformer, on_device_train_transform of the config file be adjusted after the network changes the new data set? Is the network sensitive to the parameters of config?

**Comment by drprojects** [comment]
Hi @Rambler30, please have a close look at the 🧑‍🏫 tutorial 
[slides](media/superpoint_transformer_tutorial.pdf) and 
[notebook](notebooks/superpoint_transformer_tutorial.ipynb), it was specifically created to help in this scenario. The video will also be released in the coming days.

### If you ❤️ or use this project, don't forget to give it a ⭐, it means a lot to us !
