### ISSUE TITLE
Visualisation

### ISSUE THREAD

**Issue by zeejja** [drprojects/superpoint_transformer#146]
Hello, I run the demo of visualisation and I obtained this result, but I don't know if it is the predictions that are visualised or not ? 
![image](https://github.com/user-attachments/assets/f56bc908-6586-483b-b55d-db9456942673)
![image](https://github.com/user-attachments/assets/8c228cde-adc3-47fc-8f26-67a8c1049077)

**Comment by drprojects** [comment]
These are the annotations, not the predictions. 

The answer to your question was in the [visualization documentation](https://github.com/drprojects/superpoint_transformer/blob/master/docs/visualization.md), please read the provided resources before opening an issue
