### ISSUE TITLE
 Project root directory not found in superpoint_transformer_tutorial

### ISSUE THREAD

**Issue by Schmidt-J** [drprojects/superpoint_transformer#149]
Hi, I recently heard your presentation at the 3D Academy and tried to do the superpoint_transformer_tutorial. I run into a similar issue as #23 and #59 with this error message:

```
FileNotFoundError: Project root directory not found. Indicators: ('.project-root', 'setup.cfg', 'setup.py', '.git', 'pyproject.toml')
```

Unfortunatly i don't knw how to fix this.
I'm running the code via Jupyter Notebook on a Docker container.

![grafik](https://github.com/user-attachments/assets/ebf437dd-d29a-41e0-80ab-0f5c6fec3b81)

This is what the project folder looks like at the moment:

![image](https://github.com/user-attachments/assets/6c0f5d88-9d7f-42d4-a771-e5a0d8e1fb98)

I would be glad if you could help me.

**Comment by drprojects** [comment]
Hi @Schmidt-J, have you made any modification to the codebase ? Is the notebook you are running located in the `notebooks/` directory or somewhere else on your machine ?

**Comment by Schmidt-J** [comment]
@drprojects the notebook is located in notebboks/. But i used drag and drop within jupyter notebook from a windows computer to open it, because i couldn't access the notebook from within jupyter notebook directly.

**Comment by drprojects** [comment]
> But i used drag and drop within jupyter notebook from a windows computer to open it, because i couldn't access the notebook from within jupyter notebook directly.

What do you mean ? Could you use Jupyter lab instead and open the notebook from there, by browsing files ? 

Which directory does your notebook's python interpreter live in ? 

```python
import os
os.getcwd()
```

Have you tried manually changing the path to the `notebooks/` directory at the beginning of your notebook ?

```python
import os
os.chdir('/path/to/your/superpoint_transformer/')
```

**Comment by Schmidt-J** [comment]
> Which directory does your notebook's python interpreter live in ?
/opt/notebooks

> What do you mean ? Could you use Jupyter lab instead and open the notebook from there, by browsing files ?
I cannot browse files there for some reason (I'm new to Docker).

> Have you tried manually changing the path to the notebooks/ directory at the beginning of your notebook ?
This solved the problem with the error so far:
```
import os
os.chdir('/path/to/your/superpoint_transformer/')
```
Thank you for the help.

**Comment by drprojects** [comment]
On a general note, we do not officially support nor work with Docker. So if more Docker-specific issues arise, I might not be able to help. However, I would happily to integrate any PR from you that would make the code more portable for Docker environments :wink: 

Finally, since you opened an issue here (and received some help), please remember:
### If you ❤️ or simply use this project, don't forget to give the repository a ⭐, it means a lot to us !
