### ISSUE TITLE
Is there any Installation guideline on windows or docker image ? 

### ISSUE THREAD

**Issue by MdRanaSarkar** [drprojects/superpoint_transformer#152]
Multiple times, I tried to install all packages in my windows environment but faced issues. 

Last I'm trying to test with  wsl ubuntu 24.04 on windows11. 
It would be better if there have any installation guideline on windows11 or docker.

**Comment by drprojects** [comment]
There is no installation guideline for windows, WSL, or docker, as we do not officially support any of those. As specified in the README, this project was developed on and tested for linux machines. 

We would however gladly welcome a PR for porting the installation to windows 😉
