### ISSUE TITLE
num workers

### ISSUE THREAD

**Issue by zeejja** [drprojects/superpoint_transformer#153]
Hi @drprojects , I have a question about the number of workers. I have a system with 53GB of RAM, and during training, I get the error 'dataloader's workers are out of shared memory'. I want to know if I can set the number of workers to be smaller. Thank you for your effort.

**Comment by drprojects** [comment]
Hi, yes feel free to change the number of workers if that helps on your machine. This parameter can be found at `datamodule.num_workers` in the config.
