### ISSUE TITLE
About where to find data process code.

### ISSUE THREAD

**Issue by Yangzhouzhou** [drprojects/superpoint_transformer#154]
Hello, I have recently been studying your method. Since I haven't touched Pytorch_lighting very much before, can you tell me where is the data preprocessing department in your program?

**Comment by drprojects** [comment]
Our `BaseDataset` class inherits from torch-geometric and rules how raw and preprocessed data are organized.

The behavior of the datasets (and the answer to your question) is explained in the [datasets](https://github.com/drprojects/superpoint_transformer/blob/master/docs/datasets.md) documention. Please have a look.

Also, when instantiating a dataset, the logs explicitly tell you where the preprocessed data is stored.

PS: One important novelty of our `BaseDataset` class compared to torch-geometric is that we compute a hash to characterize the `pre_transform` (ie all the preprocessing steps) of a dataset. We use this hash to uniquely identify the preprocessing recipe you have used when first instantiating a dataset, which prevents recomputing / overwriting yoir preprocessed files when instantiating your dataset with a slightly different preprocessing reciper later on.
