### ISSUE TITLE
Question about cut-pursuit

### ISSUE THREAD

**Issue by SyKszzzzz** [drprojects/superpoint_transformer#157]
Hello, it is an honor to learn about your work. Actually, I don't quite understand the replacement part of this work with the previous boost-based cut-pursuit, because the code I tried to reproduce uses cut-pursuit, but I couldn't reproduce it. I want to replace this part with the one from this project. May I ask, for example, how to implement the following line from the original cut-pursuit ([this](https://github.com/loicland/superpoint_graph/blob/0209777339327c9b327b6947af6c89b20bb45981/partition/partition.py#L177)) using the code from this project ?

```python
components, in_component = libcp.cutpursuit(features, graph_nn["source"], graph_nn["target"], graph_nn["edge_weight"], args.reg_strength) 
```

 Once again, I would like to express my respect for such an excellent work and hope I am not disturbing you.

**Comment by drprojects** [comment]
Hi @SyKszzzzz our call to cut-pursuit that resembles what you know from the Superpoint Graph implementation happens in the [`CutPursuitPartition`](https://github.com/drprojects/superpoint_transformer/blob/6cb9d930870a69c54a10be0233c156259a42e067/src/transforms/partition.py#L23) class. Have a look at how we code it there. It is important to note that the cut-pursuit implementation we are using here is the official, newer, faster, parallelized [implementation from @1a7r0ch3](https://gitlab.com/1a7r0ch3/parallel-cut-pursuit). The syntax differs a little bit from what you knew before, have a look at the documentation on the repo. If you have more questions regarding this specific piece of code, I invite you to directly post them on the [parallel cut-pursuit repo](https://gitlab.com/1a7r0ch3/parallel-cut-pursuit).

### NB: If you ❤️ or simply use this project, don't forget to give the repository a ⭐, it means a lot to us !
