### ISSUE TITLE
About cut_pursuit

### ISSUE THREAD

**Issue by zhf321** [drprojects/superpoint_transformer#159]
Dears,

I hope this message finds you well.

I am currently using cut_pursuit for superpoint segmentation, and I have encountered an issue. It works fine on the S3DIS dataset, but with the ScanNet dataset, it sometimes functions correctly and other times throws an error. I have incorporated normal information into the features within cut_pursuit, and the error I receive is "Segmentation fault, core dumped."

Have you encountered such an issue? I have tried various approaches but have not been able to resolve it. I would greatly appreciate any assistance you could provide.

Thank you for your time and support.

Best regards!

**Comment by drprojects** [comment]
Hi @zhf321 ! Did you inspect your normals (and all other features you pass to cut-pursuit) and make sure you had no NaN values in there ? If this does not solve your issue, please share a minimum reproducible example so we can have a look.

**Comment by zhf321** [comment]
Dears,

Thank you very much for your timely response amidst your busy schedule. I have checked, and it is indeed an issue related to NaN values. This is why the error is difficult to reproduce, as NaN values may or may not exist in the features required by cut_pursuit each time. The S3DIS dataset has a more uniform distribution, so the likelihood of encountering NaN values is quite low, which is why no errors occurred. In contrast, the ScanNet dataset has a sparser distribution, which may lead to some NaN values, resulting in errors.

This issue has been a concern for me for quite some time, and I am very glad that you could respond promptly and help me resolve it. Once again, thank you!

Best regards!

**Comment by drprojects** [comment]
Glad to hear you have identified the source of error ! May I close this issue then ?

**Comment by zhf321** [comment]
Yes, you may go ahead and close this issue. I appreciate your assistance and support in resolving it.

**Comment by meehirmhatrepy** [comment]
hi,
is this error below related to this issue as well?
I have checked my train and test data after preprocessing for nan values in all attributes used for partition and also point features but no nan values found.

C:\Users\user\AppData\Local\anaconda3\envs\sptx\lib\site-packages\torchmetrics\aggregation.py:77: UserWarning: Encounted `nan` values in tensor. Will be removed.
  warnings.warn("Encounted `nan` values in tensor. Will be removed.", UserWarning)
