### ISSUE TITLE
[Environment Configuration] SPT and SPG Environment Compatibility

### ISSUE THREAD

**Issue by pynsigrid** [drprojects/superpoint_transformer#16]
Hi, thanks for your excellent work in point clustering. I am interested in this field and have been working on reproducing your previous work, the SuperPoint Transformer, alongside your previous excellent project, the SuperPoint Graph.

From my understanding, SPT includes point partitioning, which is similar to that found in SPG. However, I encountered some difficulties while attempting to install the required environment for SPG, while the installation process for SPT was much smoother and successful. Therefore, I am curious to know if the SPT environment also supports the SPG project, allowing me to conduct SPG under the SPT environment.

**Comment by drprojects** [comment]
Hi @pynsigrid , thanks for your interest in our superpoint-based projects !

As indicated on the [SPG repo](https://github.com/loicland/superpoint_graph), this project is no longer maintained. 

The current project does not support SPG. It is built so as to replace SPG and does everything better:
- easier automated install
- 7x faster preprocessing
- more expressive backbone (Hierarchical partition & Transformer > single partition & Graph Neural Network)
- SOTA semantic segmentation performance
- more up-to-date DL frameworks
- hydra configs
- implements 3 datasets (S3DIS, KITTI-360, DALES)
- designed to be extended with more datasets with minor work

**Comment by loicland** [comment]
Author of SPG here. SPG and SPT use the same algorithm for partitioning: cut pursuit. All the boost functions of SPG have been reimplemented in SPT, so in theory, you could use the first level of a partitions of SPT to run SPG.

But the graph format are dofferent, so there might be a bit of work to adapt it. And like @drprojects said above, SPT does  all the same thing than SPG but better, so there is no real reason to use SPG anymore.

**Comment by pynsigrid** [comment]
Noted that. Thanks @drprojects @loicland  for your kinds explanations! It really helps me alot🥳
