### ISSUE TITLE
I have downloaded the data, how to obtain the preprocessed data

### ISSUE THREAD

**Issue by mooncakehub** [drprojects/superpoint_transformer#17]
Hi Damien:

I have prepared the s3dis dataset and do not know how to obtain the preprocessed data

└── data
    └── s3dis                                                     # Structure for S3DIS
        ├── Stanford3dDataset_v1.2.zip                              # (optional) Downloaded zipped dataset with non-aligned rooms
        ├── raw                                                     # Raw dataset files
        │   └── Area_{{1, 2, 3, 4, 5, 6}}                             # S3DIS's area/room/room.txt structure
        │       └── Area_{{1, 2, 3, 4, 5, 6}}_alignmentAngle.txt        # Room alignment angles required for entire floor reconstruction
        │       └── {{room_name}}  
        │           └── {{room_name}}.txt
        _**_**└── processed                                               # Preprocessed data
            └── {{train, val, test}}                                  # Dataset splits
                └── {{preprocessing_hash}}                              # Preprocessing folder
                    └── Area_{{1, 2, 3, 4, 5, 6}}.h5                      # Preprocessed Area file**_**_

**Comment by drprojects** [comment]
Hi @mooncakehub, thanks for your interest in the project !

Just place the downloaded `Stanford3dDataset_v1.2.zip` under `data/s3dis/Stanford3dDataset_v1.2.zip` in your `data` directory and SPT should take care of the rest :wink:

PS : if need be, see [here](https://github.com/drprojects/superpoint_transformer/blob/master/docs/datasets.md#setting-up-your-own-data-and-logs-paths) for setting up your `data` path.

Best,

Damien

**Comment by mooncakehub** [comment]
thanks for your reply! When I execute instructions：python src/train.py experiment=s3dis_11g datamodule.fold=5

I have encountered the following issues：
Traceback (most recent call last):
  File "src/train.py", line 49, in <module>
    from src import utils
  File "/home/fufu/下载/superpoint_transformer-master/src/__init__.py", line 2, in <module>
    import src.data
  File "/home/fufu/下载/superpoint_transformer-master/src/data/__init__.py", line 1, in <module>
    from .csr import *
  File "/home/fufu/下载/superpoint_transformer-master/src/data/csr.py", line 5, in <module>
    from src.utils import tensor_idx, is_sorted, indices_to_pointers, \
  File "/home/fufu/下载/superpoint_transformer-master/src/utils/__init__.py", line 11, in <module>
    from .neighbors import *
  File "/home/fufu/下载/superpoint_transformer-master/src/utils/neighbors.py", line 3, in <module>
    from src.dependencies.FRNN import frnn
ModuleNotFoundError: No module named 'src.dependencies.FRNN'

 i have already executed  ./install.sh again


⭐ Installing Parallel Cut-Pursuit

正克隆到 'src/dependencies/parallel_cut_pursuit'...
remote: Enumerating objects: 1630, done.
remote: Counting objects: 100% (563/563), done.
remote: Compressing objects: 100% (225/225), done.
remote: Total 1630 (delta 419), reused 446 (delta 335), pack-reused 1067
接收对象中: 100% (1630/1630), 77.79 MiB | 1024.00 KiB/s, 完成.
处理 delta 中: 100% (1151/1151), 完成.
正克隆到 'src/dependencies/grid_graph'...
remote: Enumerating objects: 120, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 120 (delta 9), reused 0 (delta 0), pack-reused 83
接收对象中: 100% (120/120), 65.65 KiB | 16.41 MiB/s, 完成.
处理 delta 中: 100% (39/39), 完成.
../src/cut_pursuit_d0.cpp:255:5: warning: multi-line comment [-Wcomment]
  255 |     // #pragma omp parallel for schedule(static) \
      |     ^


🚀 Successfully installed SPT

**Comment by drprojects** [comment]
Hi, your initial issue seems resolved. Please close the issue when it is solved, to keep issue topics consistent. This  makes it easier for other users using the closed issues as reference for debugging their own problems. Besides, please open an issue **only after you have investigated the problem and are stuck**. Clearly, your initial issue and your off-topic comment [here](https://github.com/drprojects/superpoint_transformer/issues/18#issuecomment-1657445503_) prove you have not even taken the time to read the `REAMDE.md` nor the provided `docs/` before opening an issue.

That being said, I will reply to your latest comment here. 

```python
ModuleNotFoundError: No module named 'src.dependencies.FRNN'
``` 

indicates you are missing the `FRNN` library. If you have a look at the `install.sh`, you will find the [lines in charge of installing `FRNN`](https://github.com/drprojects/superpoint_transformer/blob/423f1544670d6e562aed5c482571258de962e6da/install.sh#L91-L104). Please try to manually re-run these lines in your environment and see if it causes any error. If so, a quick search among the already-existing issues would lead you to this [FRNN-related issue](https://github.com/drprojects/superpoint_transformer/issues/14), which might be of help...

**Comment by weilailoveL** [comment]
Hi Damien:
When I try to run the code on windows, I get the following error：
    from cp_d0_dist import cp_d0_dist
ModuleNotFoundError: No module named 'cp_d0_dist'

I can't find a model named 'cp_d0_dist' in the code. How do I solve this problem?
