### ISSUE TITLE
Converting training output to .ckpt

### ISSUE THREAD

**Issue by enescingoz** [drprojects/superpoint_transformer#176]
Hello,

I downloaded the KITTI360 dataset and trained it using the command "python src/train.py experiment=semantic/kitti360_11g". However, in the "/log/train/runs/" folder, I only found three ".log" files and no other outputs like ".ckpt".

The "data/KITTI360/processed" folder contains subfolders for test, train, and validation, which include several ".h5" files.

Despite modifying parameters such as save_last, save_top_k, every_n_train_steps, every_n_epochs, and save_on_train_epoch_end in the "model_checkpoint.yaml" file, I am unable to generate a ".ckpt" file.

It seems that the final ".ckpt" file might be saved at the end of the training process. However, after training is completed, I encounter a "RuntimeError: DataLoader worker (pid x) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.".
I have checked similar issues here but haven't found a solution, even though my GPU memory is not fully utilized (16 GB used / 24 GB total, also have +60GB free cpu memory).

I am curious if there is a way to convert the ".h5" files in the "data/kitti360/processed" folder into a ".ckpt" file for use in example notebooks.

**Comment by drprojects** [comment]
Hello, thanks for your interest in the project !

In order to be able to process the large amount of requests we receive, we have created issue templates. These we designed to help us save time and focus on structured issues. We will no longer provide support for issues not using the provided templates, so please use them to help us help you !
