### ISSUE TITLE
Inference with batch_size > 1

### ISSUE THREAD

**Issue by tejaswi-digumarti-oxb** [drprojects/superpoint_transformer#178]
Thanks for sharing this repo. This is great work.

I am trying out the code on a custom dataset. I was able to train the model on my dataset and am able to do inference and also generate the full resolution point cloud. 

I have set `cfg.datamodule.load_full_res_idx = True` just for inference and am using this snippet
```python
predictions = trainer.predict(
        model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path
    )

nag = predictions[0]
semantic_prediction = predictions[1]
labels = semantic_prediction.full_res_semantic_pred(
   super_index_level0_to_level1=nag[0].super_index,
   sub_level0_to_raw=nag[0].sub,
   ).cpu().numpy()
```

This works fine with `batch_size=1`. How do I do the same when the `batch_size>1`.
I noticed that the NAG that gets built is the combined NAG (num_points = sum of num points of clouds in the batch (accounting for sampling)). Is there a way to split it into separate NAGs corresponding to each of the input point clouds in the batch?

**Comment by drprojects** [comment]
From what I understand, you want to reverse the `NAG` batching created with `NAG.from_nag_list()`. If so, have you tried using the `NAG.to_nag_list()` method ?

**Comment by tejaswi-digumarti-oxb** [comment]
Thanks that works for the NAG. What about the `semantic_prediction`? How do I split that up across the NAGs?

**Comment by tejaswi-digumarti-oxb** [comment]
I dug a bit into the `SemanticSegmentationOutput` object. From the `semantic_pred` object I was able to get the semantic predictions for each `NAG` by using an offset equal to the sum of the number of Level-1 nodes of all the `NAG`s before the `NAG` of interest.

The following snippet seems to work fine. Can you please let me know if this is the right way to do it?
```python
batch_predictions = predictions[batch_idx]
semantic_prediction = batch_predictions[1]
nag_list = batch_predictions[0].to_nag_list()
node_offset = 0
for i in range(len(nag_list)):
      nag = nag_list[i]

      if i > 0:
          node_offset += nag_list[i-1].num_points[1]

      labels = (
          semantic_prediction.full_res_semantic_pred(
              super_index_level0_to_level1=nag[0].super_index + node_offset,
              sub_level0_to_raw=nag[0].sub,
          )
          .cpu()
          .numpy()
      )
```

**Comment by drprojects** [comment]
Yes, that should work. The complexity you are facing is because `full_res_semantic_pred` yields an object that is larger than the number of points in `NAG[0]`, since their are more "raw" points than points in the level-0 voxelized cloud. Due to this, `NAGBatch.to_nag_list()` cannot automatically infer how to uncollate the full-resolution prediction tensor. So we need to do it "manually".

I would have coded slightly differently to make better use of already-existing mechanisms:

```python
# Run inference on a NAGBatch object. See NAGBatch.from_nag_list() and 
# NAGBatch.to_nag_list() for more details
nag_batch, output = trainer.predict(
    model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)

# Get full-res predictions on the NAGBatch object
full_res_pred_batch = output.full_res_semantic_pred(
    super_index_level0_to_level1=nag_batch[0].super_index,
    sub_level0_to_raw=nag_batch[0].sub)

# Since full_res_pred_batch contains predictions at the 'raw' level, its
# size does not match any of the Batch objects in the NAGBatch. For this 
# reason, which is specific to full-res predictions, 
# NAGBatch.from_nag_list() cannot trivially infer how to uncollate the 
# full_res_pred_batch tensor. So we need to do so manually. To this end,
# we need to identify where each batch item starts and where it ends.
# This can be inferred from the Cluster object held by nag_batch[0].sub
pointers_raw = torch.cat((
    torch.zeros(1, dtype=torch.long, device=nag_batch.device),
    nag_batch[0].sub.sizes)).cumsum(dim=0)

# To get the full-res predictions of a specific batch item we just have 
# to slice the full_res_pred_batch using the pointers
nag_fr_pred_pairs = []
for i, nag in enumerate(nag_batch.to_nag_list()):
    full_res_pred = full_res_pred_batch[pointers_raw[i]:pointers_raw[i + 1]]
    nag_fr_pred_pairs.append((nag, full_res_pred))
```

This approach should normally do the same as yours. Disclaimer: I have not tested the below snippet code :wink:. Let me know if there is a discrepancy between our approaches. In the meantime, I consider this issue solved.
