### ISSUE TITLE
Inference on own data 

### ISSUE THREAD

**Issue by aksahveoffice** [drprojects/superpoint_transformer#19]
I want to run the inference on our data using dales p retrained weights. my data classes is similar to dales data classes. how can i convert my data into proper format. or how can i run the inference on my data.

**Comment by drprojects** [comment]
Please have a look at the [guidelines](https://github.com/drprojects/superpoint_transformer/blob/master/docs/datasets.md#creating-your-own-dataset) for creating your own dataset.

An important rule (that I will make clearer in future releases) for creating your own dataset is that your points must have labels within $[0, C]$, where:
- $C$ is your `BaseDataset`'s `num_classes`
- **giving the $C$ label to a point marks it as void/ignored/unlabeled (whichever you call it) and will exclude it from metrics and losses computation**
- **all labels $[0, C - 1]$ are assumed to be present in your dataset and will be used in metrics and losses computation**

To this end, I recommend you make sure the **output of your `read_single_raw_cloud`  method never has labels outside of your $[0, C]$ range**. Besides, if some labels in $[0, C - 1]$ are not useful to you (ie absent from your dataset), I recommend you densely remap your labels to another $[0, C_2 - 1]$ range (you can use `torch_geometric.nn.pool.consecutive.consecutive_cluster` for that, for instance), while making sure you only use the label $C_2$ for void/ignored/unlabeled points.
