### ISSUE TITLE
Project root directory not found. Indicators: ('.project-root', 'setup.cfg', 'setup.py', '.git', 'pyproject.toml')

### ISSUE THREAD

**Issue by WS517** [drprojects/superpoint_transformer#23]
Hello, I am running pyrootutils.setup_ root(".", pythonpath=True).The error reported during root code is as follows:Project root directory not found. Indicators: ('.project-root', 'setup.cfg', 'setup.py', '.git', 'pyproject.toml')
How to solve it?

**Comment by drprojects** [comment]
Hello, thanks for your interest in the project.

- what command are you executing, exactly ?
- please provide the full traceback 
- have you made any modification (even minor) to the project ? 
- what is your `pyrootutils` version ?

**Comment by WS517** [comment]
> Hello, thanks for your interest in the project.
> 
> * what command are you executing, exactly ?
> * please provide the full traceback
> * have you made any modification (even minor) to the project ?
> * what is your `pyrootutils` version ?

I apologize for not articulating my question clearly.I'm trying to visualize the results, but when running demo_dales.ipynb, the above error is reported when initializing the cfg, and my version of pyrootutils is 1.0.4.This seems like a path problem but I don't know how to solve it, I would be honored if you could offer some help.

**Comment by drprojects** [comment]
Your `pyrootutils` version seems fine.

- please provide the full traceback
- have you made any modification (even minor) to the project ?
- do you have a `.git` in your project folder root ?
- are you working in a Docker environment ?

**Comment by WS517** [comment]
> Your `pyrootutils` version seems fine.
> 
> * please provide the full traceback
> * have you made any modification (even minor) to the project ?
> * do you have a `.git` in your project folder root ?
> * are you working in a Docker environment ?

I changed the demo_dals.ipynb file to a .py file and put it in pycharm to run, and I can be sure that my virtual environment is correct since I've done the training and evaluation. When I want to try to visualize the results, the compiler prompts:
 project root directory not found. indicators: ('.project-root', 'setup.cfg', 'setup.py', '.git', 'pyproject.toml'). 
I don't know how to fix this bug,I don't have .git in my project because I'm not quite sure what it's for.

**Comment by drprojects** [comment]
If you installed the project using `git clone https://github.com/drprojects/superpoint_transformer.git`, you should have a `.git` in the root of the project. This hidden folder is used by `git` for code versioning. I strongly recommend using `git` in your coding projects.

The `pyrootutils` library uses some specific files to identify the root path of the project. Please do not delete files from the provided source code. I suggest your restore all files from the initial projects before testing again.

Besides, managing paths for `hydra`, `omegaconf`, and `pyrootutils` may require some knowledge of those libraries. I cannot guarantee that your `ipynb` -> `.py` conversion will work. In particular, you will need to be careful in which directory you place your `.py` file. You may want to consider adapting your paths for local imports to work properly. See the commented line in the notebooks:

```python
# file_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # for .py script
file_path = os.path.dirname(os.path.abspath(''))  # for .ipynb notebook
```

**Comment by drprojects** [comment]
Without reply from you, I am assuming the issue is solved.
