### ISSUE TITLE
About Superpoint-Graphs Computation

### ISSUE THREAD

**Issue by HalvesChen** [drprojects/superpoint_transformer#25]
Hi, thanks for your amazing job! 
I am interested in the implementation of Superpoint-Graphs Computation, could you tell me where the implementation please?

**Comment by drprojects** [comment]
Hi @HalvesChen, thanks for your interest in the project !

If you are interested in the superpoint-graphs computation as described in [our paper](https://arxiv.org/abs/2306.08045), you will want to look into the following transforms:

- [`CutPursuitPartition`](https://github.com/drprojects/superpoint_transformer/blob/fd0ba283897403caad00fed111099120a1d1c0ec/src/transforms/partition.py#L22-L221) - computes the hierarchical partitions, on point clouds equipped with point features and an adjacency graph
- [`RadiusHorizontalGraph`](https://github.com/drprojects/superpoint_transformer/blob/fd0ba283897403caad00fed111099120a1d1c0ec/src/transforms/graph.py#L541-L699) - computes the Superpoint-Graphs for each partition level. As stated in our paper, this implementation takes an approach different from [SPG](https://arxiv.org/abs/1711.09869) to circumvent the Delaunay triangulation bottleneck.

For a better understanding of how the preprocessing works and which transforms are chained together, I invite you to have a look at the `config/datamodule/*.yaml` of your dataset of interest.

Best,

Damien
