### ISSUE TITLE
how to use the network for semantic segmentation?

### ISSUE THREAD

**Issue by mostafa501** [drprojects/superpoint_transformer#26]
Hello, this page looks very powerful.
I simply ask what are the required steps to test my own point clouds for semantic segmentation?
thank you for your help.

**Comment by drprojects** [comment]
Hi @mostafa501, thanks for your interest in the project.

Please have a look at the [datasets documentation](https://github.com/drprojects/superpoint_transformer/blob/master/docs/datasets.md#creating-your-own-dataset) for setting up your own dataset.

**Comment by mostafa501** [comment]
Hi @drprojects, thank you for the reply. I ask about the pretrained models that i can use to test my own data or i have to make the dataset (S3DIS) training and testing? how ?

Thanks

**Comment by drprojects** [comment]
I do not understand your question, pleas clarify.

**Comment by mostafa501** [comment]
Hi @drprojects, i need to test my own collected data for semantic segmentation, to tset the data i need pretrained model (checkpoint file) that used without making full training to S3DIS datasets, is this available ? how to use it?
Thank you for your interset and reply.

**Comment by drprojects** [comment]
You should find the answers on the [README](https://github.com/drprojects/superpoint_transformer/blob/master/README.md).

For running a pretrained model on a new dataset, you will need to create your own dataset. Refer to relevant indications in the [datasets documentation](https://github.com/drprojects/superpoint_transformer/blob/master/docs/datasets.md#creating-your-own-dataset).

You may also have a look at the already-existing [issues](https://github.com/drprojects/superpoint_transformer/issues?q=) where some people ask about creating their own dataset.

Finally, the code is fairly commented for you to get familiar with.

Happy coding,
Damien
