### ISSUE TITLE
How to train my own dataset

### ISSUE THREAD

**Issue by kaka-ice** [drprojects/superpoint_transformer#3]
Hello Professor！
    My point cloud only has three properties of xyz, and the fourth column is the label value, how to train my own dataset using SPT network

**Comment by drprojects** [comment]
Hello, thanks for your interest in the project !

Although radiometric information can benefit model performance, SPT can work without it.

Actually, one can easily remove the radiometric features from the provided datasets by removing `'rgb'` (for S3DIS), `'hsv'` (for KITTI-360), `'intensity'` (for DALES), from `datamodule.partition_hf` and `datamodule.point_hf`.

However, from what I gather from your message, I think you may want to create your own dataset. To this end, I invite you to have a look at the instructions [here](https://github.com/drprojects/superpoint_transformer/blob/master/docs/datasets.md#creating-your-own-dataset). 

Best,

Damien

**Comment by drprojects** [comment]
I consider this issue closed. Feel free to re-open it if necessary.
