### ISSUE TITLE
accessing checkpoint weights of PointSegmentationModule

### ISSUE THREAD

**Issue by hansoogithub** [drprojects/superpoint_transformer#38]
sorry i am having trouble accessing the trained model weights of the 
`PointSegmentationModule` and especially the encoder and the decoder, 
i would like to inspect them and edit them how can i do it? thank you

```python
cfg = init_config(overrides=[
    "experiment=kitti360",
    "ckpt_path=mycheckpoint.ckpt"
])
datamodule = hydra.utils.instantiate(cfg.datamodule)
datamodule.prepare_data()
datamodule.setup()
model = hydra.utils.instantiate(cfg.model)
model = model.load_from_checkpoint(cfg.ckpt_path, net=model.net, criterion=model.criterion)
model = model.eval().cuda()
model.state_dict() # error here
```

**Comment by drprojects** [comment]
Hi @hansoogithub 

If you only want to inspect the `state_dict`, you can simply:

```python 
ckpt = torch.load("mycheckpoint.ckpt")
```

`ckpt` is a dictionary and you will find what you want in `ckpt['state_dict']` if I am not mistaken. Otherwise just inspect the keys in `ckpt` and you should easily find it :wink:

PS: if you are interested in this project, don't forget to give our project a :star:, it matters to us !

**Comment by hansoogithub** [comment]
i gave this project a star, thank you
sorry after trying your suggestion, based on the kitti360 checkpoint

is it possible to identify which transformer blocks are the encoders and decoders in that state_dict? 
which sections are the point segmentation module? 
do the kitti360 config files determine these?

**Comment by drprojects** [comment]
> is it possible to identify which transformer blocks are the encoders and decoders in that state_dict?
which sections are the point segmentation module?

To answer these questions, I invite you to have a look at the code, it is fairly commented and should help you in understanding how the project works. In particular, check out:

- [`PointSegmentationModule`](https://github.com/drprojects/superpoint_transformer/blob/f6837bd3574c78c5d4ad800343a367e0a67c963b/src/models/segmentation.py#L21-L584) is the `pytorch-lightning`'s `LightningModule` wrapper holding the `SPT` model in its `net` attribute. Being familiar with `pytorch-lightning` will help.
- [`SPT`](https://github.com/drprojects/superpoint_transformer/blob/f6837bd3574c78c5d4ad800343a367e0a67c963b/src/models/components/spt.py#L11-L561) is the SPT model

You want to understand how these two work to be able to parse whatever you are interested in from the `state_dict`. 

> do the kitti360 config files determine these?

The configs file rely on `hydra` and have a nested inheriting structure. You can find the [model configurations](https://github.com/drprojects/superpoint_transformer/tree/f6837bd3574c78c5d4ad800343a367e0a67c963b/configs/model). To understand how these work, being familiar with `hydra` and [`lightning-hydra`](https://github.com/ashleve/lightning-hydra-template) will help.
