### ISSUE TITLE
NAG.select()

### ISSUE THREAD

**Issue by hpc100** [drprojects/superpoint_transformer#39]
Hi Damien, thank's for sharing SPT.

Environnement : NVIDIA RTX A6000 and Torch 2.0.0 // CUDA 11.7

I try to use NAG.select() and I get :
![image](https://github.com/drprojects/superpoint_transformer/assets/145356917/3d6c033b-0d89-4534-9ed9-d41274f2f3e7)
Code : 
`n = NAG.load('Area_6_conferenceRoom_1.h5') ; n.select(2, 10)`

Do you have any ideas ?

**Comment by hpc100** [comment]
I add "()" to : 

- self.keys in edge_keys() line 126
- self.keys in v_edge_keys line 141

It's a good solution ?
Thank's

**Comment by drprojects** [comment]
Hi @hpc100 

This seems might be a change in syntax wrt the `torch-geometric` version I am using. After a quick check, I noticed that a breaking change was made to the library: https://github.com/pyg-team/pytorch_geometric/pull/7629

What is your `torch_geometric` version ? I am using `torch-geometric` versions  `[2.2.0, 2.3.0, 2.3.1]` just fine on different machines. Can you please try downgrading your `torch_geometric` to one of those versions and see if it works ? 

If this solves the issue, I will look into either limiting the `torch-geometric` version or adapting the code to the new syntax.

PS: if you are interested in this project, don't forget to give our project a ⭐, it matters to us !

**Comment by hpc100** [comment]
Thank you for the quick reply.
I used 2.4.0 torch_geometric. 
I install torch_geometric 2.3.1 and it's work fine !
Thanks

**Comment by drprojects** [comment]
Cool, thanks for catching this issue ! I updated `install.sh` to prevent installing `torch-geometric` versions above `2.3` in the commit: https://github.com/drprojects/superpoint_transformer/commit/f6837bd3574c78c5d4ad800343a367e0a67c963b

Best,
Damien
