### ISSUE TITLE
Empty tensor when running inference on custom dataset

### ISSUE THREAD

**Issue by JeppeVHolm** [drprojects/superpoint_transformer#45]
Hi!

We are trying to use the pre-trained dales model to segment our dataset.  Our dataset is similar to dales and is setup in SPT in the same way as dales. When we use the dales model to segment the dales dataset we do not have any issues.
![dales_example](https://github.com/drprojects/superpoint_transformer/assets/129040179/1768dd28-4af3-4ce9-8546-71f0f468b3e8)
![kirkegaard_example](https://github.com/drprojects/superpoint_transformer/assets/129040179/5200a865-d729-4b04-bc28-08789e85c899)

When running inference we get the following error:
![image](https://github.com/drprojects/superpoint_transformer/assets/129040179/329462f3-d117-49c3-86cf-e09028d0c79f)

It seems like the 'data.pos' tensor is loaded correctly at first. However, when we run the script the tensor 'coords' is empty. As 'coords' is a result of 'data.pos'/'grid_size' we tried to change 'grid_size' as 'data.pos' seem to be read correctly. 
Furthermore we tried adding our data to the dales dataset in SPT, as we thought we might have made an error when setting up our own dataset. This did not solve the issue. 
It seems as the issue is related to the dataset, but we are having issues locating the error. Do you have any suggestions?

Once again thank you for the great project! 😃

Best regards
Jeppe

**Comment by drprojects** [comment]
Seems like you need to investigate the nature of your data before calling `grid_cluster()` [here](https://github.com/drprojects/superpoint_transformer/blob/520c1a5d4869387f3a68724337877693ec9b7890/src/transforms/sampling.py#L138):
- is `coords` empty ? 
- is `pos` empty ? 
- is `grid_size` `None` ?
- what is the shape of `pos` ? It should have a shape `(N, 3)`

**Comment by drprojects** [comment]
Have you solve this issue ? May I close it ?

**Comment by JeppeVHolm** [comment]
Hi. 
We have not yet resolved the issue. As described, our data is read as it should be. Something goes wrong when we need to create 'coords' and 'pos' as they are empty.  I think the problem is with our dataset and not SPT, so you can resolve the issue.
Best regards Jeppe

**Comment by Yarroudh** [comment]
@drprojects 
I report the same issue with custom data. My data is not empty, once passed to the Grid Sampling the pos shape becomes (0, 3) which is not correct
