### ISSUE TITLE
s3dis dataset corrupt

### ISSUE THREAD

**Issue by hansoogithub** [drprojects/superpoint_transformer#54]
when i downloaded the Stanford3dDataset_v1.2.zip 
this file in line **323473** has a symbol that makes it corrupted 
Area_5/office_19/Annotations/ceiling_1.txt

when i train using
python src/train.py experiment=s3dis datamodule.xy_tiling=2 datamodule.fold=6 
it runs fine

python src/eval.py experiment=s3dis datamodule.xy_tiling=2 datamodule.fold=6 ckpt_path=mycheckpoint
it cant run
[spt_error.txt](https://github.com/drprojects/superpoint_transformer/files/13669485/spt_error.txt)

could this data corruption cause the error?

**Comment by drprojects** [comment]
Hi. I have not encountered any corrupt data error with the `Stanford3dDataset_v1.2.zip` data, but I know that some people have build patches for some files (see [here](https://github.com/torch-points3d/torch-points3d/blob/97e10a8cf4274281ae8e482c1c3e58e4807f4e12/torch_points3d/datasets/segmentation/s3dis.md?plain=1#L6)). I also found some errors, you can find my personal patches applied when you read raw S3DIS data  [here](https://github.com/drprojects/superpoint_transformer/blob/63a2241b597dd4d906d28b9410fbfe2f220331bf/src/datasets/s3dis.py#L86).

Yet, I have not encountered any issue with `Area_5/office_19/Annotations/ceiling_1.txt`.

- Have you downloaded `Stanford3dDataset_v1.2.zip` and not `Stanford3dDataset_v1.2_Aligned_Version.zip` ?
- Have you tried re-downloading your dataset

The error you are encountering is basically saying that your cloud is empty. You will need to manually inspect what domes out of your data reader (ie `read_s3dis_room` and `read_s3dis_area`). See if any room produces an empty point cloud and why.

**Comment by drprojects** [comment]
Have you looked into this issues and fixed it ? May I close it ?

**Comment by hansoogithub** [comment]
yes place close thank you

**Comment by samira-jpg** [comment]
May I ask how this error was fixed? I'm encountering the same error!
