### ISSUE TITLE
Environment configuration issues

### ISSUE THREAD

**Issue by xiaohe3625** [drprojects/superpoint_transformer#6]
Hello, thank you for your great work. I'm currently replicating the effect in your paper, but I'm having the following problems configuring the environment:

```bash
⭐ Installing Parallel Cut-Pursuit

fatal: destination path 'src/dependencies/parallel_cut_pursuit' already exists and is not an empty directory.
fatal: destination path 'src/dependencies/grid_graph' already exists and is not an empty directory.
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cpython/cp_d0_dist_cpy.cpp
gcc: error: ../src/cp_kmpp_d0_dist.cpp: No such file or directory
error: command '/usr/bin/gcc' failed with exit code 1


🚀 Successfully installed SPT

There are no cp_kmpp_d0_dist.cpp in the path spt/superpoint_transformer-master/scripts/src/dependencies/parallel_cut_pursuit/python/cpython, only cp_d0_dist.cpp
```

**Comment by drprojects** [comment]
```bash
atal: destination path 'src/dependencies/parallel_cut_pursuit' already exists and is not an empty directory.
fatal: destination path 'src/dependencies/grid_graph' already exists and is not an empty directory.
```

It seems the dependencies folder are already there. 

Besides, your path: 

```bash
spt/superpoint_transformer-master/scripts/src/dependencies/parallel_cut_pursuit/python/cpython
```

seems to suggest the installer is looking for the `src/` directory inside `scripts`, which is quite strange to me...

Can you please try:

```bash
# More to the root directory of the git project
cd /path/to/the/project/superpoint_transformer

# Remove dependencies
rm -rf src/dependencies/parallel_cut_pursuit
rm -rf src/dependencies/grid_graph

# Clone parallel-cut-pursuit and grid-graph repos
git clone -b improve_merge https://gitlab.com/1a7r0ch3/parallel-cut-pursuit.git src/dependencies/parallel_cut_pursuit
git clone https://gitlab.com/1a7r0ch3/grid-graph.git src/dependencies/grid_graph

# Compile parallel-cut-pursuit and grid-graph
python scripts/setup_dependencies.py build_ext
```

and let me know how that goes ?

**Comment by drprojects** [comment]
After investigation, it seems this error stems from recent modifications in our
[parallel cut-pursuit dependency](https://gitlab.com/1a7r0ch3/parallel-cut-pursuit). I am looking into interfacing with the new version and will need to run some tests to make sure the partition parameterization still works the same.

In the meantime, if you want a quick fix, you can follow the procedure in `install.sh` but, with a slight modification, to compile `parallel_cut_pursuit` from a past commit : 

```bash
echo "⭐ Installing Parallel Cut-Pursuit"
echo
# Clone parallel-cut-pursuit and grid-graph repos
git clone -b improve_merge https://gitlab.com/1a7r0ch3/parallel-cut-pursuit.git src/dependencies/parallel_cut_pursuit
git clone https://gitlab.com/1a7r0ch3/grid-graph.git src/dependencies/grid_graph

# Checkout a working parallel_cut_pursuit commit
cd src/dependencies/parallel_cut_pursuit
git checkout 71ce38199c0dbf04ac9cbb61706858b3b47f5e1d
cd -

# Compile the projects
python scripts/setup_dependencies.py build_ext
```

Please let me know how that goes on your end.

**Comment by xiaohe3625** [comment]
After you update the repository, I re-download the repository and configure the environment. The following problems occur when using the python scripts/setup_dependencies.py build_ext command:

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
Traceback (most recent call last):
  File "scripts/setup_dependencies.py", line 114, in <module>
    assert osp.isfile(filepath)
AssertionError

I found that there is no name = "cp_kmpp_d0_dist_cpy"

**Comment by drprojects** [comment]
The only reason I can think of for the `cp_kmpp_d0_dist_cpy` file to be missing is that you are somehow downloading the `master` branch of the [parallel cut-pursuit repository](https://gitlab.com/1a7r0ch3/parallel-cut-pursuit.git), instead of the `improve_merge` branch.

Can you confirm that you installed the project by running `bash ./install.sh` from the project root directory and not by manually changing any command inside `install.sh` ?

Can you confirm that you executed:

```bash 
git clone -b improve_merge https://gitlab.com/1a7r0ch3/parallel-cut-pursuit.git src/dependencies/parallel_cut_pursuit
```

and not:

```bash 
git clone https://gitlab.com/1a7r0ch3/parallel-cut-pursuit.git src/dependencies/parallel_cut_pursuit
```

As a sanity check can you please run the following and let me know what you get: 

```bash
cd /path/to/the/project/superpoint_transformer
ls src/dependencies/parallel_cut_pursuit/python/cpython/
```

**Comment by xiaohe3625** [comment]
This is the result of the run：
cp_d0_dist_cpy.cpp  cp_d1_lsx_cpy.cpp  cp_d1_ql1b_cpy.cpp  cp_prox_tv_cpy.cpp

**Comment by drprojects** [comment]
I consider this issue solved. Please open a new issue for a new problem.
