### ISSUE TITLE
dataset config File Not Found (Link not referencing) 

### ISSUE THREAD

**Issue by seemab-yamin** [drprojects/superpoint_transformer#67]
I was reading the [datasets](https://github.com/TheaResearch/Segmentation_SuperPoint/blob/master/docs/datasets.md#mini-datasets) documentation and the data module link is not referring to the source.

Each dataset has a "mini" version which only processes a portion of the data, to speed up experimentation. To use it, set your the [dataset config](https://github.com/TheaResearch/Segmentation_SuperPoint/blob/master/docs/configs/datamodule) of your choice:

Missing Link:
https://github.com/TheaResearch/Segmentation_SuperPoint/blob/master/docs/configs/datamodule

Please fix this and Let me know if you need anything else from me. Thanks.

**Comment by drprojects** [comment]
Hi @seemab-yamin, thanks for pointing this out, I will modify the link in the next big release coming soon.

PS: if you use or simply like this project, don't forget to give it a ⭐, it means a lot to us !

**Comment by drprojects** [comment]
Hi all, I finally released the v2 of this project, which should address this issue :partying_face: 

Closing this issue for now, feel free to re-open if need be.
