### ISSUE TITLE
Can you provide the preprocessing code for the s3dis data set? thank you very much

### ISSUE THREAD

**Issue by gyy520cyaowu** [drprojects/superpoint_transformer#69]
I want to reproduce your code to complete my graduation project study, but there are no files in the processed directory of the data set. Can you provide the preprocessing code for the s3dis data set? Thank you very much.

**Comment by drprojects** [comment]
Hi @gyy520cyaowu thanks for your interest in our project !

All code for preprocessing, training, and evaluating on S3DIS, DALES, and KITTI-360 is available. Please refer to the `README` and the `docs/` for getting started with this project. Also, the codebase is fairly commented 😉 

PS: if you are interested in or using this project, don't forget to give our repository a ⭐, it matters to us !
