### ISSUE TITLE
Computing the NodeSize before sampling and are we really updating it ? 

### ISSUE THREAD

**Issue by gardiens** [drprojects/superpoint_transformer#75]
Hello,
Thank you for your amazing v2,
I checked the new commits and I saw that you inverted the transform NodeSize and SampleSubNodes on the on-the-fly transform ,
Unless I am right, the NodeSize compute the number of low-level node for each high-level segment, but we sample some nodes  afterwards and  this feature doesn't seem to be updated by the sampling , 
Shouldn't we either compute it after sampling or update it during the sampling? 
Sincerely, 
Pierrick

**Comment by drprojects** [comment]
Hi Pierrick,

You are correct, the `node_size` attribute is not updated after `SampleSubNodes`. In our case, we decided this was a desired behavior for several superpoint-weighted computations where we would prefer using the initial superpoint sizes (position normalization, aggregated metrics computation, etc). It is possible that the opposite order would yield similar results. Feel free to try it and let us know if you find any improvement.
Best,

Damien

**Comment by drprojects** [comment]
@gardiens, may I close this issue or are you still investigating it ?

**Comment by gardiens** [comment]
Hello , you can close it I will reopen once I got significant result :)
