### ISSUE TITLE
ERROR: Package 'pgeof' requires a different Python: 3.8.19 not in '>=3.8,~=3.12'

### ISSUE THREAD

**Issue by gyy520cyaowu** [drprojects/superpoint_transformer#83]
Running install.sh to configure the environment is full of vulnerabilities
pgeof reported an error saying that Python3.8.19 does not satisfy >=3.8,~=3.12, but python3.8 is specified in install.sh. The specific error reported is as follows:
ERROR: Package 'pgeof' requires a different Python: 3.8.19 not in '>=3.8,~=3.12'

**Comment by drprojects** [comment]
That's strange. Are you 100% sure your conda environment is using 3.18.19 ? Can you try changing to a slightly older python  3.8.16 or 3.8.16 version ? 

PS: if you are using this project, don't forget to give it a :star:, it means a lot to us

**Comment by rjanvier** [comment]
ok, sorry, I made a mistake in the python version range definition in PGEOF. I will fix that  ASAP.

**Comment by drprojects** [comment]
Thanks @rjanvier for the fix.

@gyy520cyaowu the issue likely came from pgeof, please try reinstalling now in a fresh conda environment.

**Comment by drprojects** [comment]
@gyy520cyaowu have you managed to install the project from a the latest commit, in a fresh conda environment ?
