### ISSUE TITLE
How to visualize the segmentation results of the data set

### ISSUE THREAD

**Issue by gyy520cyaowu** [drprojects/superpoint_transformer#89]
I trained and tested the dataset[s3dis], How to visualize the segmentation results of the dataset?

**Comment by drprojects** [comment]
See our provided notebooks, we provide some clear instructions for using our interactive visualization tool.

**Comment by WS517** [comment]
> I trained and tested the dataset[s3dis], How to visualize the segmentation results of the dataset?我训练并测试了数据集[s3dis]，如何可视化该数据集的分割结果？

Hello, have you had any success visualising this? I would like to communicate with you, if it's convenient can you provide me with your email? Thank you very much!
