### ISSUE TITLE
Issue in running demo

### ISSUE THREAD

**Issue by narges-tk** [drprojects/superpoint_transformer#98]
Hi! I am getting **No module named 'src.dependencies.FRNN'**  error while run demo. It's worth mentioning that inference using pre-trained model is performed nicely. Thanks in advance for your guidance.

![image](https://github.com/drprojects/superpoint_transformer/assets/47797625/3016ce70-24e0-48f4-afa7-80b68dea7be0)

**Comment by drprojects** [comment]
This means FRNN has not been correctly installed. Probably linked to your previous issue regarding FRNN. Make sure FRNN is successfully installed, in the expected location as specified in `install.sh`.

**Comment by narges-tk** [comment]
> This means FRNN has not been correctly installed. Probably linked to your previous issue regarding FRNN. Make sure FRNN is successfully installed, in the expected location as specified in `install.sh`.

Thanks for your prompt reply. The previous error is now resolved. However, I am getting the following error when run **Parsing the config files** section : 

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[12], line 2
      1 # Parse the configs using hydra
----> 2 cfg = init_config(overrides=[
      3     f"experiment={task_widget.value}/{expe_widget.value}",
      4     f"ckpt_path={ckpt_widget.value}",
      5     f"datamodule.load_full_res_idx={True}"  # only when you need full-resolution predictions 
      6 ])

File ~/DL_models/superpoint_transformer-master/src/utils/hydra.py:11, in init_config(config_name, overrides)
      9 def init_config(config_name='train.yaml', overrides=[]):
     10     GlobalHydra.instance().clear()
---> 11     pyrootutils.setup_root(".", pythonpath=True)
     12     with initialize(version_base='1.2', config_path="../../configs"):
     13         cfg = compose(config_name=config_name, overrides=overrides)

File ~/miniconda3/envs/spt/lib/python3.8/site-packages/pyrootutils/pyrootutils.py:151, in setup_root(search_from, indicator, project_root_env_var, dotenv, pythonpath, cwd)
    118 def setup_root(
    119     search_from: Union[str, Path],
    120     indicator: Union[str, Iterable[str]] = (
   (...)
    130     cwd: bool = False,
    131 ) -> Path:
    132     """Combines `get_root()` and `set_root()` into one method.
    133 
    134     Recursively searches for files from the `indicators` list, starting from given path.
   (...)
    149         Path: Path to project root.
    150     """
--> 151     path = find_root(search_from, indicator)
    152     set_root(
    153         path=path,
    154         project_root_env_var=project_root_env_var,
   (...)
    157         cwd=cwd,
    158     )
    159     return path

File ~/miniconda3/envs/spt/lib/python3.8/site-packages/pyrootutils/pyrootutils.py:73, in find_root(search_from, indicator)
     70 path = _pyrootutils_recursive_search(search_from, indicator)
     72 if not path or not path.exists():
---> 73     raise FileNotFoundError(f"Project root directory not found. Indicators: {indicator}")
     75 return path

FileNotFoundError: Project root directory not found. Indicators: ('.project-root', 'setup.cfg', 'setup.py', '.git', 'pyproject.toml')

**Comment by drprojects** [comment]
Check issue #23. Please make sure you **thoroughly investigated your problem yourself and checked passed issues before opening a new one**. We strive to provide as much support as we can here, but mind that it is quite time-consuming for us.

**Comment by narges-tk** [comment]
Resolved! Sure, sorry! Thanks for your responsibility.

**Comment by drprojects** [comment]
Also, if you ❤️ or use this project, don't forget to give it a ⭐, it means a lot to us !
